# Generated by Django 6.0.2 on 2026-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('kmCover', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=50)),
                ('imageSource', models.CharField(max_length=600)),
            ],
        ),
    ]
