# Generated by Django 6.0.2 on 2026-02-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='products',
            new_name='product',
        ),
    ]
