# Generated by Django 6.0.2 on 2026-03-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_address_order_city_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('progress', 'In Progress'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('handed_over', 'Handed Over')], default='progress', max_length=100),
        ),
    ]
